# Section 2: Numpy

## Import statements

In [2]:
import numpy

x = [1,2,3,4,5]
y = numpy.std(x) # must preface function with package name!
print(y)

1.41421356237


### as alias

In [4]:
import numpy as np

x = [1,2,3,4,5]
y = np.std(x) # must preface function with package alias!
print(y)

1.41421356237


### from package import method

In [22]:
from numpy import std, mean

x = [1,2,3,4,5]
print(std(x)) # no longer need package name!
print(mean(x))

1.41421356237
3.0


### from package import method as alias

In [18]:
from numpy import std as mystery

x = [1,2,3,4,5]
y = mystery(x) # method has been renamed!
print(y)

1.41421356237


### from package import everything

In [21]:
from numpy import * # Don't do this. BAD!

x = [1,2,3,4,5]
print(std(x))
print(mean(x))
print(median(x))

1.41421356237
3.0
3.0


## Why numpy

In [9]:
x = [1,2,3,4,5]
y = x * 3
print(y)
print(abs(x))

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


TypeError: bad operand type for abs(): 'list'

## Vectors

In [23]:
import numpy as np

### scalar multiplication

In [27]:
x = np.array([1,2,3,4,5])
y = 2 * x
print(y)

[ 2  4  6  8 10]


### exponentiation

In [ ]:
x = np.array([1,2,3,4,5])
y = x ** 2 # this is element-wise squaring. not a vector dot product.
print(y)

### addition, ones, zeros

In [32]:
x = np.array([1,2,3,4,5])
y = np.ones(5)
z = np.zeros(5)
print('x = ', x)
print('y = ', y)
print('z = ', z)
print('x + y + z = ', x+y+z)

x =  [1 2 3 4 5]
y =  [ 1.  1.  1.  1.  1.]
z =  [ 0.  0.  0.  0.  0.]
x + y + z =  [ 2.  3.  4.  5.  6.]


## Matrices

### properties

In [61]:
A = np.array([[1,2,3,4],
              [4,5,6,7],
              [7,8,9,10]])

print('Matrix A has {} elements.'.format(A.size))
print('Matrix A has {} dimensions.'.format(A.ndim))
print('Matrix A has {} rows and {} columns.'.format(A.shape[0],A.shape[1]))

Matrix A has 12 elements.
Matrix A has 2 dimensions.
Matrix A has 3 rows and 4 columns.


### slicing and access

In [110]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(A[2,2] == A[2][2])
print(A[2,2])
print(A[1:][0:2])

True
9
[[4 5 6]
 [7 8 9]]


### linear algebra

In [46]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.ones(3)
x = np.linalg.solve(A,b) # solve Ax = b
print(x)
print(np.linalg.det(A)) # matrix A is invertible!!!
print(np.dot(A,x)) # matrix multiplication
print(np.trace(A))
print(A.T) # transpose matrix A

[ 0.05 -1.1   1.05]
-9.51619735393e-16
[ 1.  1.  1.]
15
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### eye, zeros, ones

In [68]:
print(np.eye(4))
print()
print(np.zeros([3,5]))
print()
print(np.ones([5,2]))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


## Random numbers

In [95]:
x = np.random.rand(5)
print(x)
print()

A = np.random.rand(5,5) * 100
print(A)

[ 0.18062138  0.76486838  0.26031831  0.15869939  0.07626052]

[[ 55.59684534  67.0250948    0.75842515  90.65517843  46.02246132]
 [ 64.09606509   3.89079665  96.64264321  70.47692372  26.72384344]
 [ 74.91299167  73.72815726  35.48992086  71.64772122  64.26890924]
 [ 93.21755304  17.41206562  21.77924252  12.15985851  80.01351017]
 [ 87.44233508  32.29201965  75.59280728  33.21899306  78.92166788]]


## Statistical functions on matrices

In [97]:
A = np.random.rand(5,5) * 100
print(np.mean(A))
print(np.std(A))
print(np.corrcoef(A)) # correlation matrix. notice symmetry and ones on diagonal.

45.8765069775
27.6405196193
[[ 1.         -0.80071041 -0.47555239 -0.27740181  0.23139051]
 [-0.80071041  1.          0.5424405   0.04952302 -0.05838888]
 [-0.47555239  0.5424405   1.          0.6464318  -0.43728242]
 [-0.27740181  0.04952302  0.6464318   1.          0.03441625]
 [ 0.23139051 -0.05838888 -0.43728242  0.03441625  1.        ]]


## Boolean indexing

In [103]:
x = np.arange(0,10) # same as range(), but outputs a numpy array instead
evens_mask = x % 2 == 0
print(evens_mask)

x = x[evens_mask]
print(x)

[ True False  True False  True False  True False  True False]
[0 2 4 6 8]


In [107]:
A = np.random.rand(5,5) * 100
print(A)
print()

print(A[A > 75])

[[  6.3419273   56.7714717   88.77646064  85.26949985  37.48361104]
 [ 82.86608988  51.00313014  78.76775195  49.23204167  88.07764042]
 [ 34.25006613  56.58588492  11.85752293  96.77191792  62.26849047]
 [ 83.67659206   3.23357091  92.52537782  88.20532745   9.07609726]
 [ 67.10516923  84.18819469  65.39884803  24.75186787   0.431724  ]]

[ 88.77646064  85.26949985  82.86608988  78.76775195  88.07764042
  96.77191792  83.67659206  92.52537782  88.20532745  84.18819469]


## Logical operators for arrays

In [27]:
print(not True, '\n')

bools = np.array([False, True, False])
print(not bools)

False 



ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [32]:
print(bools)
print(np.logical_not(bools))
print(~bools)

[False  True False]
[ True False  True]
[ True False  True]


In [35]:
print(bools)
print(bools | True)
print(bools & False)

[False  True False]
[ True  True  True]
[False False False]


In [45]:
x = np.random.randn(100) * 100 // 1
print(x, '\n')

# print all negative odd numbers
print(x[np.logical_and(x < 0, x % 2)], '\n')

# print any negative or odd numbers
print(x[(x < 0) | (x % 2 == 1)])

[  67.   64.  108. -230.  114.   26.  -56.  136.  101.  -14. -223. -184.
  -16.  -56. -117.   68. -122.    6.  119.  -52. -220. -109. -130.   55.
   78.  101.  -35.    6.  155.   88.   30.  -37.  -29.  -60.  202.  -40.
   24.  -18.  189.  -25.  -32.   34.  132.  -96.   41. -227.   33.    9.
   21.   14.  -80.  -11.  -32.   45.  152.  -92. -246.   92.  -78.   51.
   43.  -86.    8.  -71.   11.   74.   41.  -35.  -11.   86. -118.   65.
 -145.   86. -128.  214.  -20.  -50. -131. -101.  104.  -96.  -64.  169.
  -88.   33.  -80.   51.  -56.  -41.  -93.  -23.  139.   46.  142.  -17.
   33.  -63.   16.   11.] 

[-223. -117. -109.  -35.  -37.  -29.  -25. -227.  -11.  -71.  -35.  -11.
 -145. -131. -101.  -41.  -93.  -23.  -17.  -63.] 

[  67. -230.  -56.  101.  -14. -223. -184.  -16.  -56. -117. -122.  119.
  -52. -220. -109. -130.   55.  101.  -35.  155.  -37.  -29.  -60.  -40.
  -18.  189.  -25.  -32.  -96.   41. -227.   33.    9.   21.  -80.  -11.
  -32.   45.  -92. -246.  -78.   51.   43.  